### ISSUE TITLE
Newly created Vue SFC File: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser

### ISSUE THREAD

**Issue by eyedean** [typescript-eslint/typescript-eslint#1303]
**What code were you trying to parse?**
I run into the infamous error of not finding the parser (similar to https://github.com/typescript-eslint/typescript-eslint/issues/1159 and https://github.com/typescript-eslint/typescript-eslint/issues/883) for *new Vue files* I create in my project.  **NOTE: a restart of VS and my live compiler eliminates the problem until the next time I create a new `.vue` file.**

I am using Quasar, and [vue-class-component](https://github.com/vuejs/vue-class-component) for my SFC Vue files.

Error details:
```
 error  in ./src/components/signup/CLSignupStepperHeader.vue

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/eyedean/dev/xxxxx/src/components/signup/CLSignupStepperHeader.vue
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/components/signup/CLSignupStepperHeader.vue.
The file must be included in at least one of the projects provided

✖ 1 problem (1 error, 0 warnings)


 @ ./node_modules/ts-loader??ref--10-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/signup/CLSignupStepVitals.vue?vue&type=script&lang=ts& 10:0-81 143:12-33
```

Per the request at https://github.com/typescript-eslint/typescript-eslint/issues/1159#issuecomment-558427959 I am creating this new ticket.

**What did you expect to happen?**
The new Vue file should be picked up normally.  Again, a restart of live tsc and VS code fixes it, but it kinda takes 1 minute for my project.

**What actually happened?**
It used to work flawlessly until I upgraded typescript-eslint, after a few months, recently.  Looking at https://github.com/typescript-eslint/typescript-eslint/pull/1083/commits/e3f344874368a952c607ac7167d4324287a70061 which was the fix for a similar problem, the symptom I am seeing is very related to `parsedFilesSeen` not picking up the newly created file `.vue` on-the-fly.

**Additional Notes**
Per https://eslint.vuejs.org/user-guide/#how-to-use-custom-parser for parsing Vue files, I have the following in my `.eslintrc`:
```
	parser: "vue-eslint-parser",
	
	// Must use parserOptions instead of "parser" to allow vue-eslint-parser to keep working
	// See https://eslint.vuejs.org/user-guide/#how-to-use-custom-parser
	// `parser: "vue-eslint-parser"` is already included with any "plugin:vue/**" config and should be omitted
	parserOptions: {
		project: "./tsconfig.eslint.json",
		parser: "@typescript-eslint/parser",
		sourceType: "module",
		extraFileExtensions: [".vue"]
	},
```

And then it is in my `tsconfig.eslint.json` that I am mentioning all the Vue files should be picked:
```
{
	"extends": "./tsconfig.json",
	"include": [
	  "**/*.ts",
	  "**/*.js",
	  "**/*.vue",
	  "**/*.json",
	],
	"compilerOptions": {
	  "allowJs": true,
	  "checkJs": true
	}
}
```

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.10.0` (was the same on `2.8.0`) | 
| `TypeScript`                | `3.3.3` |
| `ESLint`                    | `5.16.0` (It's on purpose to be on 5, rather than 6) |
| `node`                      | `12.3.1` |
| `npm`                       | `6.13.0` |

**Comment by yoyo930021** [comment]
If you try to upgrade TypeScript ?
I cann't reproduce.

**Comment by eyedean** [comment]
@yoyo930021 
It's ```version": "2.10.0"```

**Comment by demisx** [comment]
This also happens to me too in VS Code when a new file is added. Have to restart VS Code each time for it to go away.

* `typescript@3.5.3`
* `@typescript-eslint/parser@2.13.0`
* `@typescript-eslint/typescript-estree@2.13.0`

**Comment by armano2** [comment]
@eyedean @demisx @yoyo930021 today we merged fix for ~similar issue (not in vue sfc), can you retest it with `2.15.1-alpha.5` or provide step by step how to reproduce it?

https://github.com/typescript-eslint/typescript-eslint/pull/1412

**Comment by robbiespeed** [comment]
@armano2 I tested typescript-estree version 2.15.1-alpha.7 and it still has the issue with newly created ts/tsx files when using the vscode extension

**Comment by armano2** [comment]
@robbiespeed can you tell me step by step what are you doing (files/folders wise), or is this happening for any `.vue` file? what OS are you using?

**Comment by eyedean** [comment]
Thanks for looking into this @armano2 .

I just tested `2.15.1-alpha-7` parser, and I still have the problem.  It's even happening on my Node.js repo (only `.ts` files), so shouldn't be Vue or SFC specific.

All I do is I duplicate one of the files I have (basically create a new file with some .ts content) and it errors on the first character of the first line with the same parsing error as above.
<img width="417" alt="Screenshot at Jan 09 16-02-48" src="https://user-images.githubusercontent.com/5694695/72114826-a8e44880-32f9-11ea-8a1f-8a122a30dc88.png">

It goes away when I restart my VS Code (cmd+shift+P, Reload Window).  I am on Mac OS 10.14.5 and VS Code 1.41.1.  I have this issue constantly since like a month ago and I didn't have this issue like 3 months ago.

My feeling is for some reason the eslint service in the background (both for VS code and my Quasar CLI front-end compiler) doesn't recognize the new files **when they are created while the service is up**.  But after a restart, when it does a full new scan, it's fine with the file being already there.

**Comment by armano2** [comment]
i was able to reproduce this in simple example project, i will take a look into this

**Comment by eyedean** [comment]
Also, since it's only happening to *some of us*, I have included a screenshot of the relevant files to the configuration of eslint and typescript.

It *might be* something in the config that we are doing wrong.

<img width="975" alt="Screenshot at Jan 09 16-11-54" src="https://user-images.githubusercontent.com/5694695/72115132-d54c9480-32fa-11ea-8611-13259f97da33.png">

**Comment by armano2** [comment]
this is completly unrelated to rules or plugins

![image](https://user-images.githubusercontent.com/625469/72115362-11a5e200-3347-11ea-997d-e672b494782c.png)

if someone is interested https://github.com/armano2/typescript-eslint-1394

**Comment by robbiespeed** [comment]
It seems to only happen randomly now when creating a file in a newly created folder. 

Here's one of the errors with debug enabled:
```
2020-01-10T00:24:36.722Z eslint:ignore-pattern Check {
  filePath: '/home/rspeed/Projects/tern/src/web/components/flkjajflkafsjl/index.tsx',
  dot: false,
  relativePath: 'src/web/components/flkjajflkafsjl/index.tsx',
  result: false
}
2020-01-10T00:24:36.722Z eslint:cascading-config-array-factory Load config files for /home/rspeed/Projects/tern/src/web/components/flkjajflkafsjl.
2020-01-10T00:24:36.722Z eslint:cascading-config-array-factory Cache hit: /home/rspeed/Projects/tern/src/web/components/flkjajflkafsjl.
2020-01-10T00:24:36.722Z eslint:cli-engine Lint /home/rspeed/Projects/tern/src/web/components/flkjajflkafsjl/index.tsx
2020-01-10T00:24:36.722Z eslint:linter Linting code for /home/rspeed/Projects/tern/src/web/components/flkjajflkafsjl/index.tsx (pass 1)
2020-01-10T00:24:36.722Z eslint:linter Verify
2020-01-10T00:24:36.722Z eslint:linter With ConfigArray: /home/rspeed/Projects/tern/src/web/components/flkjajflkafsjl/index.tsx
2020-01-10T00:24:36.792Z eslint:linter Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/web/components/flkjajflkafsjl/index.tsx.
The file must be included in at least one of the projects provided.
Error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/web/components/flkjajflkafsjl/index.tsx.
The file must be included in at least one of the projects provided.
    at Object.createProjectProgram (/home/rspeed/Projects/tern/node_modules/@typescript-eslint/typescript-estree/dist/create-program/createProjectProgram.js:58:15)
    at getProgramAndAST (/home/rspeed/Projects/tern/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:60:32)
    at Object.parseAndGenerateServices (/home/rspeed/Projects/tern/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:294:30)
    at Object.parseForESLint (/home/rspeed/Projects/tern/node_modules/@typescript-eslint/parser/dist/parser.js:53:51)
    at parse (/home/rspeed/Projects/tern/node_modules/eslint/lib/linter/linter.js:640:22)
    at Linter._verifyWithoutProcessors (/home/rspeed/Projects/tern/node_modules/eslint/lib/linter/linter.js:1111:33)
    at Linter._verifyWithConfigArray (/home/rspeed/Projects/tern/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (/home/rspeed/Projects/tern/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (/home/rspeed/Projects/tern/node_modules/eslint/lib/linter/linter.js:1400:29)
    at verifyText (/home/rspeed/Projects/tern/node_modules/eslint/lib/cli-engine/cli-engine.js:230:48)
2020-01-10T00:24:36.792Z eslint:linter Generating fixed text for /home/rspeed/Projects/tern/src/web/components/flkjajflkafsjl/index.tsx (pass 1)
```
<details>
<summary>System / Project Details</summary>
os: Linux (Fedora 30)
vscode: 1.14.0
eslint extension: microsoft/eslint 2.0.13
eslint: 6.7.2
typescript-eslint/eslint-plugin: 2.15.0
typescript-eslint/parser: 2.15.0
typescript-eslint/typescript-estree: 2.15.1-alpha.7

tsconfig.json
```
{
  "compilerOptions": {
    "noEmit": true,
    "lib": [
      "ES2020",
      "DOM"
    ],
    "target": "ES2019",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowJs": false,
    "jsx": "preserve",
    "jsxFactory": "createElement",
    "experimentalDecorators": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "suppressImplicitAnyIndexErrors": true,
  }
}
```
(Also tried adding `"include": "./**/*"`)

.eslintrc.json
```
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "ignorePatterns": [
    "/.nyc_output",
    "/build",
    "/coverage",
    "/node_modules"
  ],
  "rules": {
    "@typescript-eslint/class-name-casing": "error",
    "@typescript-eslint/indent": ["error", 2, {
      "SwitchCase": 1,
      // to work around bugs, see https://github.com/typescript-eslint/typescript-eslint/milestone/1
      "ignoredNodes": [
        "CallExpression[typeParameters]",
        "TSTypeParameterInstantiation",
        "TSTypeAnnotation > TSParenthesizedType",
        "TSFunctionType > TSTypeAnnotation"
      ]
    }],
    "@typescript-eslint/member-delimiter-style": [
      "error",
      {
        "multiline": {
          "delimiter": "semi",
          "requireLast": true
        },
        "singleline": {
          "delimiter": "semi",
          "requireLast": false
        }
      }
    ],
    "@typescript-eslint/no-for-in-array": "error",
    "@typescript-eslint/no-require-imports": "error",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-namespace-keyword": "error",
    "@typescript-eslint/quotes": [
      "error",
      "single",
      {
        "allowTemplateLiterals": true
      }
    ],
    "@typescript-eslint/semi": [
      "error",
      "always"
    ],
    "@typescript-eslint/space-before-function-paren": ["error"],
    "@typescript-eslint/type-annotation-spacing": "error",
    "arrow-parens": [
      "error",
      "always"
    ],
    "brace-style": [
      "error",
      "stroustrup"
    ],
    "camelcase": "error",
    "curly": "error",
    "eqeqeq": [
      "error",
      "smart"
    ],
    "id-blacklist": "off",
    "id-match": "off",
    // disabled in favour of @typescript-eslint/indent
    "indent": "off",
    "keyword-spacing": "error",
    "max-len": [
      "error",
      {
        "code": 100
      }
    ],
    "new-parens": "error",
    "no-eval": "error",
    "no-redeclare": "error",
    "no-trailing-spaces": "error",
    "no-unsafe-finally": "error",
    "no-var": "error",
    "object-curly-spacing": ["error", "always"],
    "prefer-const": "error",
    // disabled in favour of @typescript-eslint/quotes
    "quotes": "off",
    "semi-spacing": ["error", {"before": false, "after": true}],
    "space-before-blocks": "error",
    // disabled in favour of @typescript-eslint/space-before-function-paren
    "space-before-function-paren": "off",
    "space-in-parens":"error",
    "space-infix-ops": ["error", { "int32Hint": false }],
    "spaced-comment": "error"
  }
}
```
</details>

**Comment by armano2** [comment]
```diff
- "include": ["**/*.ts", "**/*.js", "**/*.vue", "**/*.json"]
+ "include": ["./**/*.ts", "./**/*.js", "./**/*.vue", "./**/*.json"]
```

this temporarily solves it for vue and ts files, now question is why 😸

**Comment by armano2** [comment]
Small update about my research:
- this is vue specific issue (its present for other any custom extension)
- this issue can be reproduced only within vscode (its working correctly in other editors that i tested)
- root cause: for some reason in typescript triggers to many folders into watch (./src and ./) and that causes our validation to fail
- i'm unable to reproduce this within unit tests, 
- This issue seems to be related to what vscode or vscode-eslint does to typescript (code base of those projects is to big for me to find where and why)
- I opened ticket about this in vscode-eslint -> maybe they will be able to help me understand whats going on there https://github.com/microsoft/vscode-eslint/issues/872
- On our side there is way to patch this issue by marking registered directories recursively that matches specified path https://github.com/typescript-eslint/typescript-eslint/pull/1424/commits/967114b29dd198160aff7cefb2ae17af84c84acb but i'm unable to test this outisde vscode
- while working on this ticket i discovered one more issue with persisted parse that relative paths was not correctly watched #1424

**Comment by robbiespeed** [comment]
> this is not vue specific issue (its present for any custom extension)

What is meant by custom extension? 
It's happening with .ts and .tsx files as well, but I haven't found the steps that reproduce it consistently.

**Comment by armano2** [comment]
custom -> not supported naively by typescript (ts, tsx, js, jsx, json)

in vscode setting i changed file association of *.test to typescript and i was having same issue

**Comment by armano2** [comment]
> It's happening with .ts and .tsx files as well, but I haven't found the steps that reproduce it consistently.

as for ts and tsx files: vscode is starting failing on all files after first vue file is created

**Comment by robbiespeed** [comment]
@armano2 I have only tsx and ts files in my project and it's still happening. I'll try and create an example project to reproduce.

**Comment by cgwic** [comment]
My temporary solution: additional tsconfigs for files with errors. In my case one tsconfig for every problem directory.

**Comment by eyedean** [comment]
Thanks for working on this @armano2 and @bradzacher.  Please let me know when it's going to be out, so I can verify and confirm that the fix is working for both my .ts and .vue projects.  Thanks! 🙌

**Comment by armano2** [comment]
it should be live already you can check alpha version `2.15.1-alpha.14`

**Comment by eyedean** [comment]
Magic! 🎉  I confirm that it's now fixed for both `.ts` and `.vue` files in `2.15.1-alpha.16`.  Thanks a lot, @armano2 !
