### ISSUE TITLE
Change from base.json to base.ts breaks vscode-eslint

### ISSUE THREAD

**Issue by joelday** [typescript-eslint/typescript-eslint#2193]
Unsure whose bug this is, but latest version of the ESLint extension along with the latest version of @typescript-eslint/eslint-plugin is now failing with:

```
Referenced from: /Users/****/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at readFile (/Users/****/node_modules/eslint/lib/cli-engine/config-array-factory.js:118:15)
    at loadJSONConfigFile (/Users/****/node_modules/eslint/lib/cli-engine/config-array-factory.js:156:41)
    at loadConfigFile (/Users/****/node_modules/eslint/lib/cli-engine/config-array-factory.js:290:20)
    at ConfigArrayFactory._loadConfigData (/Users/****/node_modules/eslint/lib/cli-engine/config-array-factory.js:496:13)
(node:80940) UnhandledPromiseRejectionWarning: Error: Cannot read config file: /Users/****/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json
Error: ENOENT: no such file or directory, open '/Users/****/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.json'
```

Does not repro when running from CLI.

**Comment by joelday** [comment]
I'm unable to repro this now. I believe it was due to some kind of stale state during configuration changes/reinstalls.

**Comment by thisismydesign** [comment]
Having the same issue, when / where did this change from `base.json` happen?

**Comment by thisismydesign** [comment]
Found it: https://github.com/typescript-eslint/typescript-eslint/pull/2001/files#diff-70f87c2f4f2000db4ee56ee4fa39237e

Had to revert back to before `v3.0.0`. Please reopen this issue.

**Comment by bradzacher** [comment]
Given the very few number of users who have reported this, and given that I know of many project that are using it in VSCode without issue - I believe this is due to local version mismatches and caching.

If you can find provide a consistent reproduction case, I'm happy to reopen and investigate.

**Comment by thisismydesign** [comment]
@bradzacher Here you go: https://github.com/c-hive/cra-typescript-boilerplate

- Open in VSCode
- Install extensions from `.vscode/extensions.json`
- `yarn install`
- Create a new file, e.g. `app.js`, add a few empty lines, save the file
- Notice autofix doesn't kick in
- Check the output of ESLint in the console (picture below)
- In `.eslintrc.js` remove `"plugin:@typescript-eslint/recommended"`
- Save the file again, notice autofix now works

![image](https://user-images.githubusercontent.com/3299948/85793872-f896bf00-b735-11ea-9b3b-5a7c6d6e4285.png)

I'm also quite curious as to how this isn't a problem for many more people. The breaking change was introduced more than a month ago now.

**Comment by bradzacher** [comment]
Your repro doesn't repro for me - I cloned your repo, and followed the steps as described, and it worked perfectly
![image](https://user-images.githubusercontent.com/7462525/85807524-084adf00-b707-11ea-80c8-d0c1c02331a6.png)

As mentioned before - likely you have an issue with your local install being in a bad state.
Try nuking your `node_modules`, and restarting vscode.

**Comment by thisismydesign** [comment]
I did that several times.

To make sure: linting errors show up in the editor for me as well, that's not the issue. Did you do the exact steps outlined? Did you check the output of ESLint in the console? The specific issue for me is the broken autofix on save. Did that work for you?

**Comment by bradzacher** [comment]
> Did you do the exact steps outlined

- Open in VSCode
- required extensions were already installed
- `yarn install`
- Create a new file, `test.tsx`, and add the code `const x = 'a';`
- See lint error about quotes being incorrect show up in editor.
- Hit save
  - quotes are fixed, and lint message clears
- Undo change and use the manual fix command
  - quotes are fixed, and lint message clears
- Undo change and use the "ESLint: Fix all auto-fixable Problems" command from command palette.
  - quotes are fixed, and lint message clears
- Check the output of ESLint in the console
  - see no errors.

**Comment by sweeetland** [comment]
FYI I am also experiencing this issue. On a brand new machine too so I highly doubt is to do with left over node_modules.

**Comment by bradzacher** [comment]
The common denominator between two of you is `create-react-app`.
CRA includes their package `react-scripts`, which includes all of their tooling for doing everything.

The current release of CRA (3.4.1) does not yet support v3 of our tooling.
https://github.com/facebook/create-react-app/blob/v3.4.1/packages/react-scripts/package.json#L33-L34
Additionally, that same release still runs ESLint v6.
https://github.com/facebook/create-react-app/blob/v3.4.1/packages/react-scripts/package.json#L45

It's worth noting that their unreleased master branch is upgraded to ESLint v7, and v3 of our tooling.

This means that in the above setups that did standard CRA init, followed by a manual install of both ESLint and our packages - the package manager would has installed two versions of ESLint and our packages - one for the version that CRA has a dependency on, and one for the latest version that was manually installed.

Having a quick look at @thisismydesign's `yarn.lock` it shows exactly that, multiple versions of each of our packages have been installed.

https://github.com/c-hive/cra-typescript-boilerplate/blob/37949de1aff83dac6e328a380bfb39c328bb0da3/yarn.lock#L1648-L1669
https://github.com/c-hive/cra-typescript-boilerplate/blob/37949de1aff83dac6e328a380bfb39c328bb0da3/yarn.lock#L4373-L4456

**Why is this a problem?**

ESLint does its own module resolution etc - it doesn't solely rely upon node's module resolution

In v6, ESLint resolved all plugins from the current working directory by default unless otherwise specified.
In v7, there was a breaking change to how it loaded files, and it now loads plugins relative to the config file itself. https://eslint.org/docs/user-guide/migrating-to-7.0.0#plugin-loading-change

So with multiple versions of ESLint and of our packages installed, it's probably a bit of luck of the draw as to what version gets loaded by which tool and when.

---

With all that being said, I go back to my original point:

> likely you have an issue with your local install being in a bad state.

**Comment by thisismydesign** [comment]
@bradzacher Thanks a lot! You seem to be correct, restarting my computer seems to have resolved the issue for now.

That said, I still don't fully get how this can happen. I don't think loading a self-contained version of either `v2.34.0` or `v3.4.0` would be an issue. What seemed to have happened is [code from `v2.34.0`](https://github.com/typescript-eslint/typescript-eslint/blob/v2.34.0/packages/eslint-plugin/src/index.ts) was loading [a file from `v3.4.0`](https://github.com/typescript-eslint/typescript-eslint/blob/v3.4.0/packages/eslint-plugin/src/configs/base.ts).

I don't have a clear way to reproduce the solution (recreating `node_modules` might be one, but restarting the computer was not on my list of things to try so far). Do you think we can / should report this somewhere else?

**Comment by bradzacher** [comment]
I believe this is just some weirdness that's happening due to the different version of ESLint's different config loading strategies. ESLint v6 had a really bad strategy, which is why they reverted it in v7.

The reason that it breaks is because you've got two versions installed. If you only had on version installed it would work perfectly because that install would be hoisted into the root node_modules.

I believe that it does something along the lines of:
- load the root eslintrc
- see `plugin:@typescript-eslint/recommended`
- load the plugin `@typescript-eslint/eslint-plugin`
- the plugin exports a variable `configs.recommended`, which has the property `extends: ["./configs/base.json"]`
- because this is a relative path, ESLint uses its own algorithm to find the file.
  - because v6 was crappy here - it goes back to the project root, and attempts to resolve the plugin folder from there.
  - attempts to load from `node_modules/@typescript-eslint/dist/configs/base.json`
  - because the root version of this package is v3, this loading crashes.

ESLint v7 shouldn't have this issue.
If you only have one version of ESLint and our tooling, this shouldn't be an issue.

There's not really anything to report really unless you want to spend the time figuring out a consistent repro that you can give to one a maintainer to investigate.

The advice I can give you is: ensure you are you using the versions of packages supported by your tooling.
In this case, just uninstall all of the local versions of eslint etc, and use the versions required by CRA. When they do their next release, you will get the new versions of the packages.

**Comment by thisismydesign** [comment]
That makes sense @bradzaBrad, thanks for the detailed explanation.
